# Generated by Django 5.0.6 on 2024-07-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_title_forma_field1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forma',
            old_name='field2',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='forma',
            old_name='field1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='formb',
            old_name='field2',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='formb',
            old_name='field1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='formc',
            old_name='field2',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='formc',
            old_name='field1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='forma',
            name='user',
        ),
        migrations.RemoveField(
            model_name='formb',
            name='user',
        ),
        migrations.RemoveField(
            model_name='formc',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('user_a', 'User A'), ('user_b', 'User B'), ('user_c', 'User C')], default='user_a', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
