# Generated by Django 5.0.6 on 2024-07-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_field2_forma_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forma',
            old_name='name',
            new_name='field_a',
        ),
        migrations.RenameField(
            model_name='formb',
            old_name='name',
            new_name='field_b',
        ),
        migrations.RenameField(
            model_name='formc',
            old_name='name',
            new_name='field_c',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='forma',
            name='description',
        ),
        migrations.RemoveField(
            model_name='formb',
            name='description',
        ),
        migrations.RemoveField(
            model_name='formc',
            name='description',
        ),
    ]
