# Generated by Django 5.0.6 on 2024-07-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_name_forma_field_a_rename_name_formb_field_b_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormA',
        ),
        migrations.DeleteModel(
            name='FormB',
        ),
        migrations.DeleteModel(
            name='FormC',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
