# Generated by Django 5.0.6 on 2024-07-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_can_manage_form_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_manage_form_a',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='can_manage_form_b',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='can_manage_form_c',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
