# Generated by Django 5.0.6 on 2024-07-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_can_manage_form_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='field',
            field=models.EmailField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
